export const mn = {
  admin: 'Админ',
  brand: 'foody',
  subtitle: 'foody платформын өгөгдөл удирдах',
  refresh: 'Шинэчлэх',
  loading: 'Ачааллаж байна...',
  loadError: 'Ачаалахад алдаа гарлаа',
  noRecords: 'Бүртгэл олдсонгүй',
  add: 'Нэмэх',
  save: 'Хадгалах',
  saving: 'Хадгалж байна...',
  cancel: 'Цуцлах',
  edit: 'Засах',
  delete: 'Устгах',
  active: 'Идэвхтэй',
  inactive: 'Идэвхгүй',
  free: 'Үнэгүй',
  confirmDelete: (name: string) => `"${name}"-г устгах уу?`,
  pages: {
    dashboard: 'Хяналтын самбар',
    users: 'Хэрэглэгчид',
    restaurants: 'Ресторанууд',
    dishes: 'Хоолнууд',
    orders: 'Захиалгууд',
    categories: 'Ангиллууд',
    payments: 'QPay төлбөр',
    notifications: 'Push мэдэгдэл',
    couriers: 'Жолооч нар',
  },
  couriers: {
    subtitle: 'Жолоочийн утас, нэр, нууц үгийг энд бүртгэнэ. Мобайл апп-аар нэвтэрнэ.',
    add: 'Жолооч нэмэх',
    passwordRequired: 'Нууц үг оруулна уу',
    newPassword: 'Шинэ нууц үг',
    passwordHint: 'Хоосон үлдвэл хуучин нууц үг хэвээр',
  },
  notifications: {
    subtitle: 'FCM ашиглан апп хэрэглэгчид мэдэгдэл илгээнэ',
    serviceStatus: 'Үйлчилгээний төлөв',
    fcmConfigured: 'FCM тохиргоо',
    registeredDevices: 'Бүртгэлтэй төхөөрөмж',
    setupHint:
      'Backend .env файлд FIREBASE_SERVICE_ACCOUNT_PATH эсвэл FIREBASE_SERVICE_ACCOUNT_JSON тохируулна уу.',
    compose: 'Мэдэгдэл бичих',
    composeHint: 'Гарчиг, агуулга оруулаад илгээнэ үү',
    titleLabel: 'Гарчиг',
    titlePlaceholder: 'Жишээ: Flash хямдрал эхэллээ',
    bodyLabel: 'Агуулга',
    bodyPlaceholder: 'Мэдэгдлийн дэлгэрэнгүй текст...',
    typeLabel: 'Төрөл',
    targetLabel: 'Хүлээн авагч',
    userLabel: 'Хэрэглэгч',
    selectUser: 'Хэрэглэгч сонгох...',
    send: 'Илгээх',
    sending: 'Илгээж байна...',
    types: {
      promo: 'Хямдрал',
      system: 'Систем',
      order: 'Захиалга',
    },
    targets: {
      all: 'Бүх хэрэглэгч',
      user: 'Нэг хэрэглэгч',
    },
  },
  paymentStatus: {
    pending: 'Хүлээгдэж буй',
    paid: 'Төлсөн',
    expired: 'Хугацаа дууссан',
    cancelled: 'Цуцлагдсан',
  },
  orderStatus: {
    active: 'Идэвхтэй',
    delivered: 'Хүргэгдсэн',
    cancelled: 'Цуцлагдсан',
  },
  preOrder: {
    badge: 'Урьдчилсан',
    scheduledFor: 'Захиалсан цаг',
    fulfillmentType: 'Авах арга',
    delivery: 'Хүргэлтээр',
    pickup: 'Очиж идэх',
  },
  orderActions: {
    preparing: 'Бэлтгэгдсэн',
    out_for_delivery: 'Хүргэлтэнд гарсан',
    delivered: 'Хүргэгдсэн',
    cancelled: 'Цуцлах',
  },
  trackingStep: 'Одоогийн алхам',
  markDelivered: 'Хүргэгдсэн гэж тэмдэглэх',
  ordersPage: {
    assignCourier: 'Жолоочид хуваарилах',
    selectCourier: 'Жолооч сонгох',
    assignedCourier: 'Хуваарилсан жолооч',
    noCouriers: 'Идэвхтэй жолооч байхгүй байна',
    assign: 'Хуваарилах',
    assigning: 'Хуваарилж байна...',
  },
  logout: 'Гарах',
  fields: {
    name: 'Нэр',
    phone: 'Утас',
    email: 'И-мэйл',
    role: 'Төрөл',
    membership: 'Гишүүнчлэл',
    points: 'Оноо',
    orders: 'Захиалга',
    avatarUrl: 'Зураг URL',
    slug: 'Slug',
    location: 'Байршил',
    deliveryFee: 'Хүргэлтийн төлбөр',
    rating: 'Үнэлгээ',
    imageUrl: 'Зураг URL',
    images: 'Зургууд',
    imagesHint: 'Олон зураг сонгож Cloudinary руу хуулна',
    imagesUploading: 'Хуулж байна...',
    selectCategory: 'Ангилал сонгох',
    freeDelivery: 'Үнэгүй хүргэлт',
    price: 'Үнэ',
    category: 'Ангилал',
    restaurant: 'Ресторан',
    sortOrder: 'Эрэмбэ',
    icon: 'Icon',
    invoiceId: 'Нэхэмжлэх ID',
    senderInvoiceNo: 'Дотоод дугаар',
    orderId: 'Захиалгын ID',
    amount: 'Дүн',
    description: 'Тайлбар',
    status: 'Төлөв',
    qpayShortUrl: 'QPay холбоос',
    qrText: 'QR текст',
    callbackUrl: 'Callback URL',
    paidAt: 'Төлсөн огноо',
    expiresAt: 'Дуусах огноо',
    password: 'Нууц үг',
  },
  dialogs: {
    newUser: 'Шинэ хэрэглэгч',
    editUser: 'Хэрэглэгч засах',
    newRestaurant: 'Шинэ ресторан',
    editRestaurant: 'Ресторан засах',
    newDish: 'Шинэ хоол',
    editDish: 'Хоол засах',
    newCategory: 'Шинэ ангилал',
    editCategory: 'Ангилал засах',
    newPayment: 'Шинэ QPay төлбөр',
    editPayment: 'QPay төлбөр засах',
    newCourier: 'Шинэ жолооч',
    editCourier: 'Жолооч засах',
  },
} as const;
