export const mn = {
  admin: 'Админ',
  brand: 'foody',
  subtitle: 'foody платформын өгөгдөл удирдах',
  refresh: 'Шинэчлэх',
  loading: 'Ачааллаж байна...',
  loadError: 'Ачаалахад алдаа гарлаа',
  noRecords: 'Бүртгэл олдсонгүй',
  add: 'Нэмэх',
  save: 'Хадгалах',
  saving: 'Хадгалж байна...',
  cancel: 'Цуцлах',
  edit: 'Засах',
  delete: 'Устгах',
  active: 'Идэвхтэй',
  inactive: 'Идэвхгүй',
  free: 'Үнэгүй',
  confirmDelete: (name: string) => `"${name}"-г устгах уу?`,
  pages: {
    dashboard: 'Хяналтын самбар',
    users: 'Хэрэглэгчид',
    restaurants: 'Ресторанууд',
    dishes: 'Хоолнууд',
    orders: 'Захиалгууд',
    categories: 'Ангиллууд',
    payments: 'QPay төлбөр',
  },
  paymentStatus: {
    pending: 'Хүлээгдэж буй',
    paid: 'Төлсөн',
    expired: 'Хугацаа дууссан',
    cancelled: 'Цуцлагдсан',
  },
  orderStatus: {
    active: 'Идэвхтэй',
    delivered: 'Хүргэгдсэн',
    cancelled: 'Цуцлагдсан',
  },
  orderActions: {
    preparing: 'Бэлтгэгдсэн',
    out_for_delivery: 'Хүргэлтэнд гарсан',
    delivered: 'Хүргэгдсэн',
    cancelled: 'Цуцлах',
  },
  trackingStep: 'Одоогийн алхам',
  markDelivered: 'Хүргэгдсэн гэж тэмдэглэх',
  logout: 'Гарах',
  dialogs: {
    newUser: 'Шинэ хэрэглэгч',
    editUser: 'Хэрэглэгч засах',
    newRestaurant: 'Шинэ ресторан',
    editRestaurant: 'Ресторан засах',
    newDish: 'Шинэ хоол',
    editDish: 'Хоол засах',
    newCategory: 'Шинэ ангилал',
    editCategory: 'Ангилал засах',
    newPayment: 'Шинэ QPay төлбөр',
    editPayment: 'QPay төлбөр засах',
  },
  fields: {
    name: 'Нэр',
    phone: 'Утас',
    email: 'И-мэйл',
    role: 'Төрөл',
    membership: 'Гишүүнчлэл',
    points: 'Оноо',
    orders: 'Захиалга',
    avatarUrl: 'Зураг URL',
    slug: 'Slug',
    location: 'Байршил',
    deliveryFee: 'Хүргэлтийн төлбөр',
    rating: 'Үнэлгээ',
    imageUrl: 'Зураг URL',
    freeDelivery: 'Үнэгүй хүргэлт',
    price: 'Үнэ',
    category: 'Ангилал',
    restaurant: 'Ресторан',
    sortOrder: 'Эрэмбэ',
    icon: 'Icon',
    invoiceId: 'Нэхэмжлэх ID',
    senderInvoiceNo: 'Дотоод дугаар',
    orderId: 'Захиалгын ID',
    amount: 'Дүн',
    description: 'Тайлбар',
    status: 'Төлөв',
    qpayShortUrl: 'QPay холбоос',
    qrText: 'QR текст',
    callbackUrl: 'Callback URL',
    paidAt: 'Төлсөн огноо',
    expiresAt: 'Дуусах огноо',
  },
} as const;
